name = "hyperaion-lp"
main = "src/worker.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = ["/hyperaion", "/hyperaion/", "/hyperaion/lp", "/hyperaion/lp/*"]
